[package]
name = "lambda-normal"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
lambda-flows = "0.2"
serde_json = "1.0"
flowsnet-platform-sdk = "=0.1.3"
log = "0.4"
